version: '3'
services:
  postgres:
    image: "postgres"
    container_name: db_container
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    networks:
      - net_go_app

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "gui@alura.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres

  go_app:
    image: go_app:latest
    container_name: go_app
    networks:
      - net_go_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  net_go_app: {}
