name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2.2.1

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        # Artifact name
        name: go_app_executable
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.HUB_DOCKER_USERNAME}}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.HUB_DOCKER_PASSWORD}}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: auto
        # Log out from the Docker registry at the end of a job
        logout: true

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: 10diieggos/go_ci_app:${{ github.ref_name }}